// Code generated by yo. DO NOT EDIT.
// Package customtypes contains the types.
package customtypes

import (
	"context"
	"fmt"

	"cloud.google.com/go/spanner"
	"google.golang.org/grpc/codes"
)

// SourceTable represents a row from 'SourceTable'.
type SourceTable struct {
	ID  int64  `spanner:"ID" json:"ID"`   // ID
	Val string `spanner:"Val" json:"Val"` // Val
}

func SourceTablePrimaryKeys() []string {
	return []string{
		"ID",
	}
}

func SourceTableColumns() []string {
	return []string{
		"ID",
		"Val",
	}
}

func SourceTableWritableColumns() []string {
	return []string{
		"ID",
		"Val",
	}
}

func (st *SourceTable) columnsToPtrs(cols []string, customPtrs map[string]interface{}) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		if val, ok := customPtrs[col]; ok {
			ret = append(ret, val)
			continue
		}

		switch col {
		case "ID":
			ret = append(ret, &st.ID)
		case "Val":
			ret = append(ret, &st.Val)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}
	return ret, nil
}

func (st *SourceTable) columnsToValues(cols []string) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		switch col {
		case "ID":
			ret = append(ret, st.ID)
		case "Val":
			ret = append(ret, st.Val)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}

	return ret, nil
}

// newSourceTable_Decoder returns a decoder which reads a row from *spanner.Row
// into SourceTable. The decoder is not goroutine-safe. Don't use it concurrently.
func newSourceTable_Decoder(cols []string) func(*spanner.Row) (*SourceTable, error) {
	customPtrs := map[string]interface{}{}

	return func(row *spanner.Row) (*SourceTable, error) {
		var st SourceTable
		ptrs, err := st.columnsToPtrs(cols, customPtrs)
		if err != nil {
			return nil, err
		}

		if err := row.Columns(ptrs...); err != nil {
			return nil, err
		}

		return &st, nil
	}
}

// Insert returns a Mutation to insert a row into a table. If the row already
// exists, the write or transaction fails.
func (st *SourceTable) Insert(ctx context.Context) *spanner.Mutation {
	values, _ := st.columnsToValues(SourceTableWritableColumns())
	return spanner.Insert("SourceTable", SourceTableWritableColumns(), values)
}

// Update returns a Mutation to update a row in a table. If the row does not
// already exist, the write or transaction fails.
func (st *SourceTable) Update(ctx context.Context) *spanner.Mutation {
	values, _ := st.columnsToValues(SourceTableWritableColumns())
	return spanner.Update("SourceTable", SourceTableWritableColumns(), values)
}

// InsertOrUpdate returns a Mutation to insert a row into a table. If the row
// already exists, it updates it instead. Any column values not explicitly
// written are preserved.
func (st *SourceTable) InsertOrUpdate(ctx context.Context) *spanner.Mutation {
	values, _ := st.columnsToValues(SourceTableWritableColumns())
	return spanner.InsertOrUpdate("SourceTable", SourceTableWritableColumns(), values)
}

// UpdateColumns returns a Mutation to update specified columns of a row in a table.
func (st *SourceTable) UpdateColumns(ctx context.Context, cols ...string) (*spanner.Mutation, error) {
	// add primary keys to columns to update by primary keys
	colsWithPKeys := append(cols, SourceTablePrimaryKeys()...)

	values, err := st.columnsToValues(colsWithPKeys)
	if err != nil {
		return nil, newErrorWithCode(codes.InvalidArgument, "SourceTable.UpdateColumns", "SourceTable", err)
	}

	return spanner.Update("SourceTable", colsWithPKeys, values), nil
}

// FindSourceTable gets a SourceTable by primary key
func FindSourceTable(ctx context.Context, db YORODB, id int64) (*SourceTable, error) {
	key := spanner.Key{id}
	row, err := db.ReadRow(ctx, "SourceTable", key, SourceTableColumns())
	if err != nil {
		return nil, newError("FindSourceTable", "SourceTable", err)
	}

	decoder := newSourceTable_Decoder(SourceTableColumns())
	st, err := decoder(row)
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "FindSourceTable", "SourceTable", err)
	}

	return st, nil
}

// ReadSourceTable retrieves multiples rows from SourceTable by KeySet as a slice.
func ReadSourceTable(ctx context.Context, db YORODB, keys spanner.KeySet) ([]*SourceTable, error) {
	var res []*SourceTable

	decoder := newSourceTable_Decoder(SourceTableColumns())

	rows := db.Read(ctx, "SourceTable", keys, SourceTableColumns())
	err := rows.Do(func(row *spanner.Row) error {
		st, err := decoder(row)
		if err != nil {
			return err
		}
		res = append(res, st)

		return nil
	})
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "ReadSourceTable", "SourceTable", err)
	}

	return res, nil
}

// Delete deletes the SourceTable from the database.
func (st *SourceTable) Delete(ctx context.Context) *spanner.Mutation {
	values, _ := st.columnsToValues(SourceTablePrimaryKeys())
	return spanner.Delete("SourceTable", spanner.Key(values))
}
