// Code generated by yo. DO NOT EDIT.
// Package customtypes contains the types.
package customtypes

import (
	"context"
	"fmt"

	"cloud.google.com/go/spanner"
	"google.golang.org/api/iterator"
	"google.golang.org/grpc/codes"
)

// ViewLayer1 represents a row from 'ViewLayer1'.
type ViewLayer1 struct {
	ID  int64  `spanner:"ID" json:"ID"`   // ID
	Val string `spanner:"Val" json:"Val"` // Val
}

func ViewLayer1PrimaryKeys() []string {
	return []string{
		"ID",
	}
}

func ViewLayer1Columns() []string {
	return []string{
		"ID",
		"Val",
	}
}

func ViewLayer1WritableColumns() []string {
	return []string{
		"ID",
		"Val",
	}
}

func (vl *ViewLayer1) columnsToPtrs(cols []string, customPtrs map[string]interface{}) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		if val, ok := customPtrs[col]; ok {
			ret = append(ret, val)
			continue
		}

		switch col {
		case "ID":
			ret = append(ret, &vl.ID)
		case "Val":
			ret = append(ret, &vl.Val)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}
	return ret, nil
}

func (vl *ViewLayer1) columnsToValues(cols []string) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		switch col {
		case "ID":
			ret = append(ret, vl.ID)
		case "Val":
			ret = append(ret, vl.Val)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}

	return ret, nil
}

// newViewLayer1_Decoder returns a decoder which reads a row from *spanner.Row
// into ViewLayer1. The decoder is not goroutine-safe. Don't use it concurrently.
func newViewLayer1_Decoder(cols []string) func(*spanner.Row) (*ViewLayer1, error) {
	customPtrs := map[string]interface{}{}

	return func(row *spanner.Row) (*ViewLayer1, error) {
		var vl ViewLayer1
		ptrs, err := vl.columnsToPtrs(cols, customPtrs)
		if err != nil {
			return nil, err
		}

		if err := row.Columns(ptrs...); err != nil {
			return nil, err
		}

		return &vl, nil
	}
}

// FindViewLayer1 gets a ViewLayer1 by primary key
func FindViewLayer1(ctx context.Context, db YORODB, id int64) (*ViewLayer1, error) {
	const sqlstr = "SELECT " +
		"ID, Val " +
		"FROM ViewLayer1 " +
		"WHERE ID = @param0"
	stmt := spanner.NewStatement(sqlstr)
	stmt.Params["param0"] = id
	iter := db.Query(ctx, stmt)
	defer iter.Stop()
	row, err := iter.Next()
	if err != nil {
		if err == iterator.Done {
			return nil, newErrorWithCode(codes.NotFound, "FindViewLayer1", "ViewLayer1", err)
		}
		return nil, newError("FindViewLayer1", "ViewLayer1", err)
	}

	decoder := newViewLayer1_Decoder(ViewLayer1Columns())
	vl, err := decoder(row)
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "FindViewLayer1", "ViewLayer1", err)
	}

	return vl, nil
}
